#version: '3.8.0'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbSmartPricing
    user: root
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: dbSmartPricing
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./database/mySQL:/docker-entrypoint-initdb.d
